config/routes.rb
Rails.application.routes.draw do
  resources :keyboard_items
  root to: "home#index"
  devise_for :users, controllers: {
        session: "users/sessions"
  }

  get "/basket_items" => "basket_items#index"
  get "/basket_items/:id" => "basket_items#show"
  delete "/basket_items/:id" => "basket_items#destroy"
  post "/basket_items" => "basket_items#create"
  post "/basket_items/purchase_all" => "basket_items#purchase_all"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :user
  belongs_to :keyboard_item
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  before_action :set_basket_item, only: %i[ show destroy ]
  before_action :authenticate_user!

  # GET /basket_items or /basket_items.json
  def index
    @keyboard_items = current_user.basket_items.collect { |basket_item| basket_item.keyboard_item }
  end

  # GET /basket_items/1 or /basket_items/1.json
  def show
  end

  def purchase_all
    purchased_items=0
    failed_items=0
    current_user.basket_items.each do |basket_item|
      keyboard_item = basket_item.keyboard_item
      if keyboard_item.amount >= 1
        keyboard_item.amount -= 1
        keyboard_item.save
        basket_item.destroy!
        purchased_items += 1
      else
        failed_items += 1
      end
    end

    if failed_items == 0
      respond_to do |format|
        format.html { redirect_to basket_items_path, status: :see_other, notice: "Purchased all ("+purchased_items.to_s+") items." }
        format.json { head :no_content }
      end
    elsif purchased_items > 0
      respond_to do |format|
        format.html { redirect_to basket_items_path, status: :see_other, notice: "Purchased "+purchased_items.to_s+" items.", alert: "Failed to purchase "+failed_items.to_s+" items." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to basket_items_path, status: :see_other, alert: "Failed to purchase all ("+failed_items.to_s+") items." }
        format.json { head :no_content }
      end
    end
  end

  # POST /basket_items or /basket_items.json
  def create
    filtered_params = basket_item_params
    @basket_item = BasketItem.new(filtered_params)
    @basket_item.user = current_user

    @keyboard_item = KeyboardItem.find(filtered_params[:keyboard_item_id])
    if @keyboard_item == nil
      respond_to do |format|
        format.html { redirect_to keyboard_items_path, status: :precondition_failed, alert: "Keyboard item does not exist." }
        format.json { head :no_content, status: :precondition_failed }
        return
      end
    end

    respond_to do |format|
      if @basket_item.save
        format.html { redirect_to @keyboard_item, notice: "Item added to basket." }
        format.json { render :show, status: :created, location: @basket_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basket_items/1 or /basket_items/1.json
  def destroy
    if @basket_item == nil
      respond_to do |format|
        format.html { redirect_to basket_items_path, status: :precondition_failed, alert: "Item does not exist in basket." }
        format.json { head :no_content, status: :precondition_failed }
        return
      end
    end

    if @basket_item.user == current_user
      keyboard_item = @basket_item.keyboard_item
      @basket_item.destroy!

      respond_to do |format|
        format.html { redirect_to keyboard_item, status: :see_other, notice: "Item removed from basket." }
        format.json { head :no_content }
      end

      return
    end

    respond_to do |format|
      format.html { redirect_to basket_items_path, status: :precondition_failed, alert: "Item does not exist in basket." }
      format.json { head :no_content, status: :precondition_failed }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket_item
      @basket_item = BasketItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def basket_item_params
      params.require(:basket_item).permit(:keyboard_item_id)
    end
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/views/basket_items/_basket_item.html.erb
<div id="<%= dom_id basket_item %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= basket_item.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Keyboard item:</strong>
    <%= basket_item.keyboard_item_id %>
  </p>

</div>

app/views/basket_items/_form.html.erb
<%= form_with(model: basket_item, class: "contents") do |form| %>
  <% if basket_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(basket_item.errors.count, "error") %> prohibited this basket_item from being saved:</h2>

      <ul>
        <% basket_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :keyboard_item_id %>
    <%= form.text_field :keyboard_item_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/basket_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing basket item</h1>

  <%= render "form", basket_item: @basket_item %>

  <%= link_to "Show this basket item", @basket_item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to basket items", basket_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/basket_items/index.html.erb
<div class="w-full">

  <% content_for :title, "Basket items" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Basket items</h1>
    <% if current_user.basket_items.length > 0 %>
      <%= button_to "Purchase all", basket_items_path+"/purchase_all", class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="keyboard_items" class="flex flex-wrap gap-2 items-center">
    <% @keyboard_items.each do |keyboard_item| %>
      <%= render keyboard_item %>
    <% end %>
  </div>
</div>

app/views/basket_items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New basket item</h1>

  <%= render "form", basket_item: @basket_item %>

  <%= link_to "Back to basket items", basket_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/basket_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @basket_item %>

    <%= link_to "Edit this basket item", edit_basket_item_path(@basket_item), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to basket items", basket_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this basket item", @basket_item, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>