config/routes.rb
Rails.application.routes.draw do
  resources :keyboard_items
  root to: "home#index"
  devise_for :users, controllers: {
        session: "users/sessions"
  }

  get "/basket_items" => "basket_items#index"
  get "/basket_items/:id" => "basket_items#show"
  delete "/basket_items/:id" => "basket_items#destroy"
  post "/basket_items" => "basket_items#create"
  post "/basket_items/purchase_all" => "basket_items#purchase_all"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/keyboard_item.rb
class KeyboardItem < ApplicationRecord
  has_many :basket_items, dependent: :destroy
  has_many :users, through: :basket_items

  def self.ransackable_attributes(auth_object = nil)
    ["manufacturer", "name"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/keyboard_items_controller.rb
class KeyboardItemsController < ApplicationController
  before_action :set_keyboard_item, only: %i[ show edit update destroy ]

  # GET /keyboard_items or /keyboard_items.json
  def index
    @q = KeyboardItem.ransack(params[:q])
    @keyboard_items = @q.result(distinct: true)
  end

  # GET /keyboard_items/1 or /keyboard_items/1.json
  def show
  end

  # GET /keyboard_items/new
  def new
    unless user_signed_in? && current_user.admin?
      respond_to do |format|
        format.html { redirect_to keyboard_items_path, status: :see_other, alert: "Invalid permission." }
      end
    end
    @keyboard_item = KeyboardItem.new
  end

  # GET /keyboard_items/1/edit
  def edit
    unless user_signed_in? && current_user.admin?
      respond_to do |format|
        format.html { redirect_to @keyboard_item, status: :see_other, alert: "Invalid permission." }
      end
    end
  end

  # POST /keyboard_items or /keyboard_items.json
  def create
    unless user_signed_in? && current_user.admin?
      respond_to do |format|
        format.html { redirect_to keyboard_items_path, status: :see_other, alert: "Invalid permission." }
        format.json { head :no_content, status: :see_other }
      end
      return
    end

    @keyboard_item = KeyboardItem.new(keyboard_item_params)

    respond_to do |format|
      if @keyboard_item.save
        format.html { redirect_to @keyboard_item, notice: "Keyboard item was successfully created." }
        format.json { render :show, status: :created, location: @keyboard_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @keyboard_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keyboard_items/1 or /keyboard_items/1.json
  def update
    unless user_signed_in? && current_user.admin?
      respond_to do |format|
        format.html { redirect_to @keyboard_item, status: :see_other, alert: "Invalid permission." }
        format.json { head :no_content, status: :see_other }
      end
      return
    end

    respond_to do |format|
      if @keyboard_item.update(keyboard_item_params)
        format.html { redirect_to @keyboard_item, notice: "Keyboard item was successfully updated." }
        format.json { render :show, status: :ok, location: @keyboard_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @keyboard_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keyboard_items/1 or /keyboard_items/1.json
  def destroy
    unless user_signed_in? && current_user.admin?
      respond_to do |format|
        format.html { redirect_to @keyboard_item, status: :see_other, alert: "Invalid permission." }
        format.json { head :no_content, status: :see_other }
      end
      return
    end
    @keyboard_item.destroy!

    respond_to do |format|
      format.html { redirect_to keyboard_items_path, status: :see_other, notice: "Keyboard item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyboard_item
      @keyboard_item = KeyboardItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def keyboard_item_params
      params.require(:keyboard_item).permit(:name, :description, :manufacturer, :amount, :price)
    end
end

app/helpers/keyboard_items_helper.rb
module KeyboardItemsHelper
end

app/views/keyboard_items/_form.html.erb
<%= form_with(model: keyboard_item, class: "contents") do |form| %>
  <% if keyboard_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(keyboard_item.errors.count, "error") %> prohibited this keyboard_item from being saved:</h2>

      <ul>
        <% keyboard_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/keyboard_items/_keyboard_item.html.erb
<div id="<%= dom_id keyboard_item %>" class="max-w-sm rounded overflow-hidden shadow-md bg-white">
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2"><%= keyboard_item.name %></div>
    <p class="text-gray-700 text-base">
      <%= keyboard_item.description %>
    </p>
  </div>
  <div class="px-6 pt-4 pb-2">
    <p class="inline-block px-3 py-1  mr-2 mb-2 bg-gray-200 rounded-full">
      <strong class="font-medium mb-1">Manufacturer:</strong>
      <%= keyboard_item.manufacturer %>
    </p>
    <p class="inline-block px-3 py-1  mr-2 mb-2 bg-gray-200 rounded-full">
      <strong class="font-medium mb-1">Amount:</strong>
      <%= keyboard_item.amount %>
    </p>
    <p class="inline-block px-3 py-1  mr-2 mb-2 bg-gray-200 rounded-full">
      <strong class="font-medium mb-1">Price:</strong>
      €<%= number_with_precision(keyboard_item.price, precision: 2) %>
    </p>

    <%unless current_page?(keyboard_item_path(keyboard_item))%>
    <%= link_to "View item", keyboard_item, class: "inline-block px-3 py-1 mr-2 mb-2 bg-blue-500 hover:bg-blue-700 rounded-full font-medium text-white" %>
    <%end%>
    
  </div>
</div>

app/views/keyboard_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing keyboard item</h1>

  <%= render "form", keyboard_item: @keyboard_item %>

  <%= link_to "Show this keyboard item", @keyboard_item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to keyboard items", keyboard_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/keyboard_items/index.html.erb
<div class="w-full">
  <% content_for :title, "Keyboard items" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Keyboard items</h1>
    <%= search_form_for @q, class: "mb-4" do |f| %>
      <div class="flex gap-3 align-items-center">
        <%= f.search_field :name_or_manufacturer_cont, class: "block shadow rounded-full border border-gray-400 outline-none w-72 px-2 py-2 w-full", placeholder: "Search by name or manufacturer..." %>
        <%= f.submit "Search", class: "rounded-full py-3 px-5 bg-blue-600 text-white block font-medium" %>
      </div>
    <% end %>
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to "New keyboard item", new_keyboard_item_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>
  <div id="keyboard_items" class="flex flex-wrap gap-2 items-center">
    <% @keyboard_items.each do |keyboard_item| %>
      <%= render keyboard_item %>
    <% end %>
  </div>
</div>

app/views/keyboard_items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New keyboard item</h1>

  <%= render "form", keyboard_item: @keyboard_item %>

  <%= link_to "Back to keyboard items", keyboard_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/keyboard_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%# <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">Notice</p> %>

    <%= link_to "Back", keyboard_items_path, class: "rounded-lg mb-2 py-3 px-5 bg-blue-200 inline-block font-medium" %>
    <%= render @keyboard_item %>

    <% if user_signed_in?%>
      <div class="flex flex-col">
        <% if current_user.keyboard_items.include?(@keyboard_item) %>
          <%= button_to "Remove from basket", basket_items_path+"/"+current_user.basket_items.select {|basket_item| basket_item.keyboard_item==@keyboard_item}[0].id.to_s, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-blue-200 font-medium" %>
        <% elsif (@keyboard_item.amount > 0) %>
          <%= button_to "Add to basket", basket_items_path, method: :post, class: "mt-2 rounded-lg py-3 px-5 bg-blue-200 font-medium", params: { basket_item: { keyboard_item_id: @keyboard_item.id }} %>
        <% end %>
        <% if current_user.admin? %>
          <%= button_to "Edit this keyboard item", edit_keyboard_item_path(@keyboard_item), method: :get, class: "mt-2 rounded-lg py-3 px-5 bg-blue-200 font-medium" %>
          <%= button_to "Destroy this keyboard item", @keyboard_item, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-blue-200 font-medium" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>