config/routes.rb
Rails.application.routes.draw do
  resources :keyboard_items
  root to: "home#index"
  devise_for :users, controllers: {
        session: "users/sessions"
  }

  get "/basket_items" => "basket_items#index"
  get "/basket_items/:id" => "basket_items#show"
  delete "/basket_items/:id" => "basket_items#destroy"
  post "/basket_items" => "basket_items#create"
  post "/basket_items/purchase_all" => "basket_items#purchase_all"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Krazy Keys" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/kbIcon.png" type="image/png">
    <link rel="icon" href="/kbIcon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/kbIcon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-cyan-50">
    <div>
      <div class="fixed top-0 left-0 right-0">
        <div class="bg-white flex border-b pl-2 pr-2 pt-2 pb-px">
          <ul class="flex">  
            <li class="ml-1 mr-1 flex-shrink h-9 flex">
              <img src="/kbIcon.png" alt="KrazyKeys Logo" class="flex-shrink"/>
            </li>
            <li class="ml-1 mr-5">
              <h1 class="font-bold text-3xl">Krazy Keys</h1>
            </li>
            <%= render "nav_tab", target: "/" , label:"Home", full:true%>
            <%= render "nav_tab", target: keyboard_items_path , label:"Keyboards"%>
            <% if user_signed_in? %>
              <%= render "nav_tab", target: basket_items_path , label:"Basket"%>
            <% end %>
          </ul>
          <div class="flex-grow align-middle"></div>
          
          <% if user_signed_in? %>
            <%= button_to destroy_user_session_path, method: :delete, class: "rounded-full px-5 bg-blue-200 inline-block font-medium text-base align-middle" do %>
              <i class="bi bi-box-arrow-right"></i> Log Out
            <% end %>
          <% else %>
            <%= button_to new_user_registration_path, method: :get, class: "ml-1 rounded-full px-5 bg-blue-200 inline-block font-medium text-base align-middle" do %>
              <i class="bi bi-box-arrow-right"></i> Sign Up
            <% end %>
            <%= button_to new_user_session_path, method: :get, class: "ml-1 rounded-full px-5 bg-blue-200 inline-block font-medium text-base align-middle" do %>
              <i class="bi bi-box-arrow-right"></i> Log In
            <% end %>
          <% end %>
          <%# <button class="rounded-full px-5 bg-blue-200 inline-block font-medium text-base">
            Hello
          </button> %> 
        </div>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative <%= alert.present? ? '':'hidden' %>" role="alert">
          <strong class="font-bold">Alert:</strong>
          <span class="block sm:inline"><%=alert%></span>
          <%# <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
          </span> %>
        </div>
        <div class="flex items-center bg-blue-500 text-white text-sm font-bold px-4 py-3 <%=notice.present? ? '':'hidden' %>" role="alert">
          <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
          <p><%=notice%></p>
        </div>
      </div>
      <div>
        <div class="h-12"></div>
        <div class="h-12 <%=alert.present? ? '':'hidden' %>"></div>
        <div class="h-10 <%=notice.present? ? '':'hidden' %>"></div>

        <main class="container mx-auto mt-5 mb-5 flex">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>